- name: OpenTofu deploy
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  vars:
    ansible_shell_allow_world_readable_temp: true

  tasks:
    - name: Zielverzeichnis anlegen
      file:
        path: /opt/tofu/deploy
        state: directory
        mode: '0755'

    - name: main.tf übertragen
      copy:
        src: "{{ playbook_dir }}/main.tf"
        dest: /opt/tofu/deploy/main.tf

    - name: variables.tf übertragen
      copy:
        src: "{{ playbook_dir }}/variables.tf"
        dest: /opt/tofu/deploy/variables.tf

    - name: tofu init
      command: tofu init -input=false -reconfigure
      args:
        chdir: /opt/tofu/deploy
      environment:
        TF_HTTP_ADDRESS: "https://gitlab.isgus.de/api/v4/projects/31/terraform/state/opentofu"
        TF_HTTP_LOCK_ADDRESS: "https://gitlab.isgus.de/api/v4/projects/31/terraform/state/opentofu/lock"
        TF_HTTP_UNLOCK_ADDRESS: "https://gitlab.isgus.de/api/v4/projects/31/terraform/state/opentofu/lock"
        TF_HTTP_LOCK_METHOD: "POST"
        TF_HTTP_UNLOCK_METHOD: "DELETE"

    - name: tofu apply
      command: tofu apply -input=false -auto-approve
      args:
        chdir: /opt/tofu/deploy
      environment:
        TF_VAR_vcenter_password: "{{ vcenter_password }}"
        TF_HTTP_ADDRESS: "https://gitlab.isgus.de/api/v4/projects/31/terraform/state/opentofu"
        TF_HTTP_LOCK_ADDRESS: "https://gitlab.isgus.de/api/v4/projects/31/terraform/state/opentofu/lock"
        TF_HTTP_UNLOCK_ADDRESS: "https://gitlab.isgus.de/api/v4/projects/31/terraform/state/opentofu/lock"
        TF_HTTP_LOCK_METHOD: "POST"
        TF_HTTP_UNLOCK_METHOD: "DELETE"