---
- ansible.builtin.import_tasks: preflight.yml
- ansible.builtin.import_tasks: gitlab_update.yml

- ansible.builtin.include_tasks:
    file: "{{ role_path }}/../k8s_cluster_common/tasks/tofu_apply.yml"
